# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-owncloud

# >> macros
%define debug_package %{nil}
%define __requires_exclude ^libqwebdav|libnemonotifications-qt5.*$
%define __provides_exclude_from ^%{_datadir}/.*$
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    ownCloud
Version:    0.4
Release:    1
Group:      Qt/Qt
License:    GPLv2
URL:        https://github.com/beidl/harbour-owncloud
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-owncloud.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Unofficial ownCloud client for SailfishOS

%package daemon
Summary:   ownCloud background task for automatic camera backups

%description daemon
ownCloud background task for automatic camera backups

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# >> files
# << files

%files daemon
%defattr(-,root,root,-)
%{_bindir}/%{name}-daemon
/usr/lib/systemd/user/%{name}-daemon.service

%post daemon
/bin/systemctl-user enable harbour-owncloud-daemon.service >/dev/null 2>&1 || :
/bin/systemctl-user restart harbour-owncloud-daemon.service >/dev/null 2>&1 || :
