name: ghostcloud
version: git
grade: stable
confinement: strict
base: core24
summary: A modern cross-platform client for Nextcloud, ownCloud, WebDav.
description: |
  Allows you to easily access your NextCloud, ownCloud and WebDav
  instances with a cross-platform, native Free Software application.

  Features:
    - Support for NextCloud, ownCloud & WebDav
    - File management
    - Document previews
    - Video & audio previews
    - Storage usage information

  Also available on Android, SailfishOS & postmarketOS.

platforms:
  amd64:
  arm64:
  armhf:

package-repositories:
  - type: apt
    url: http://repo.ubports.com/
    key-id: B551C909D750AA744948E9ED4BD4B4D6DBB583F1
    components: [ main ]
    suites: [ 24.04-2.x ]

apps:
  ghostcloud:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/lomiri-launch
    command: usr/bin/harbour-owncloud
    plugs:
      - x11
      - wayland
      - mir
      - maliit
      - desktop
      - desktop-legacy
      - opengl
      - alsa
      - pulseaudio
      - home
      - removable-media
      - network
      - audio-playback
      - media-hub
      - online-accounts-service
      - ghostcloud-daemon
  daemon:
    command-chain:
      - bin/gpu-2404-wrapper # For libicui18n.so.74
      - bin/lomiri-launch # For all the required Qt goodness
    command: usr/bin/harbour-owncloud-daemon
    daemon: simple
    daemon-scope: user
    plugs:
      - network
      - home
      - online-accounts-service
    slots:
      - ghostcloud-service

plugs:
  lomiri-ui-toolkit:
    interface: content
    target: $SNAP/lomiri-ui-toolkit
    default-provider: lomiri-ui-toolkit-core24
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  ghostcloud-daemon:
    interface: dbus
    bus: session
    name: com.github.beidl.HarbourOwncloud.Daemon.Uploader

slots:
  ghostcloud-service:
    interface: dbus
    bus: session
    name: com.github.beidl.HarbourOwncloud.Daemon.Uploader

layout:
  /usr/share/X11/xkb:
    symlink: $SNAP/lomiri-ui-toolkit/usr/share/X11/xkb
  /usr/share/icons:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /usr/share/qt5:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/qt5
  /usr/share/alsa:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/alsa

parts:
  ghostcloud:
    plugin: qmake
    source: .
    qmake-parameters:
      - CONFIG+=snap
      - CONFIG+=ubuntutouch
      - CONFIG+=nopermissionagent
      - CONFIG+=noqmlextension
      - CONFIG+=nosharing
      - CONFIG+=quickcontrols
    qmake-project-file: harbour-owncloud.pro
    build-packages:
      - wget
      - make
      - qt5-qmake
      - qttools5-dev
      - build-essential
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - libqt5xmlpatterns5-dev
      - qtmultimedia5-dev
      - libqt5webkit5-dev
      - qtbase5-dev
      - qtquickcontrols2-5-dev
      - qml-module-qtquick2
      - qml-module-qtgraphicaleffects
      - qml-module-qtquick-window2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-extras
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qtquick-controls
      - qml-module-qt-labs-settings
      - qml-module-qtquick-localstorage
      - liblomiri-download-manager-client-dev
      - liblomiri-online-accounts-qt5-dev
    override-build: |
        craftctl default
        #cd $CRAFT_PART_SRC
        #qmake CONFIG+=noadditionals CONFIG+=quickcontrols
        #make -j$(nproc --all)
        #DESTDIR=$CRAFT_PART_INSTALL make install
    override-prime: |
        craftctl default
        mkdir -p ${CRAFT_PRIME}/bin
        wget "https://gitlab.com/ubports/development/core/packaging/snaps/lomiri-ui-toolkit-core24/-/raw/main/misc/command-chain/lomiri-launch"
        mv lomiri-launch ${CRAFT_PRIME}/bin/lomiri-launch
        chmod 755 ${CRAFT_PRIME}/bin/lomiri-launch
  gpu-2404:
    after:
      - ghostcloud
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      git config --global --add safe.directory $CRAFT_PROJECT_DIR
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
